print("WELCOME TO START-UP FILE")
print("------------------------")
import mysql.connector
con = mysql.connector.connect(host="localhost", user="root", passwd="mysql12345")
mycursor = con.cursor()
def setup():
    print('')
    print('HELLO USER!')
    print('-----------')
    ch=int(input("(1)Rules\n(2)Setup\n(3)Help\n(4)Exit\nEnter:"))
    print('')
    if(ch==1):
        print('BASIC THINGS AND PROCEDURES FOR RUNNING THIS CODE')
        print('-------------------------------------------------')
        print('1)Before running the main file, you need to setup your program using choice(2) in this file\n2)Open the IDLE version of both the files and type in the password for your root mysql user\n')
        print('3)After that, open the main program and use as per your requirements :)')
        print('')
        print('NOTE: THE ABOVE STEPS ARE FOR THE FIRST-TIME INITIALISING, YOU CAN ALSO USE THE "HELP" CHOICE HERE AS WELL AS IN EACH BLOCK OF THE MAIN PROGRAM TO KNOW MORE DETAILS ABOUT THE CODE')
        print('CAUTION: THERE IS A CHANCE OF AN UNEXPECTED UNBOUND ERROR ON OVER USE OF "BACK" FUNCTIONS WHILE EXITING THE PROGRAM, DO NOT PANIC!!!')
        print('')
        setup()
    elif(ch==2):
        print('Setting up may take a while...')
        mycursor.execute("DROP DATABASE IF EXISTS bankofe") 
        mycursor.execute("CREATE DATABASE bankofe")
        mycursor.execute("USE Library")
        mycursor.execute("CREATE TABLE customerdetails (cust_id INT(5) NOT NULL PRIMARY KEY,name VARCHAR(50) NOT NULL,address VARCHAR(150),dob DATE NOT NULL,kvc_docnum VARCHAR(20),gender INT(1) NOT NULL,phone VARCHAR(10) NOT NULL,email_id VARCHAR(50),occupation VARCHAR(30));")
        mycursor.execute("CREATE TABLE customerbalance (cust_id INT(5) NOT NULL PRIMARY KEY,balance INT(20),last_transaction_time TIMESTAMP );")
        mycursor.execute("CREATE TABLE transactions(transac_id INT(9) NOT NULL PRIMARY KEY,dcust INT(5) NOT NULL,ccust INT(5) NOT NULL,amount BIGINT(20) NOT NULL,time TIMESTAMP NOT NULL );")
        mycursor.execute("CREATE TABLE credentials (userid VARCHAR(20) NOT NULL PRIMARY KEY,pwd VARCHAR(30) NOT NULL,cust_id INT(5) NOT NULL,admin INT(1) NOT NULL );")
        print('')
        n=int(input('Enter no. of admins to manage the bank:'))
        for i in range(n):
            a=int(input('Enter Supervisor ID:'))
            b=str(input('Enter Supervisor username:'))
            c=str(input('Enter Password:'))
            sql='insert into credentials(SP_ID,Name,Password) values(%s,%s,%s)'
            rol=[(a,b,c)]
            mycursor.executemany(sql, rol)
            print('')
        print('---YOUR PROGRAM HAS BEEN SUCCESSFULLY SETUP, NOW YOU CAN RUN YOUR PROGRAM---')
        print('')
        print("!!!CAUTION:DON'T RUN THIS PROGRAM AGAIN UNLESS YOU WANT TO REBOOT YOUR LIBRARY(ERASE ALL DATA)!!!")
        con.commit()
        setup()
    elif(ch==3):
        print("HELP")
        print("----")
        print("Option (1) lets you see the basic things before using the program to get an idea about the program\nOption (2) is used for creating the required tables for the program. This should be used only once!")
        setup()
    elif(ch==4):
        print("GOOD-BYE!")
        con.close()
setup()
